"""
app/models/surge.py
───────────────────
Stores historical surge events and ML model predictions.
Used by the Celery analytics task and the predictive endpoint.
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Float, Integer, String, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base_class import Base


class SurgeEvent(Base):
    """
    Recorded every time surge was detected during a comparison.
    Provides the training dataset for the predictive model.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    platform: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    hour_of_day: Mapped[int] = mapped_column(Integer, nullable=False)
    day_of_week: Mapped[int] = mapped_column(Integer, nullable=False)  # 0=Mon, 6=Sun
    surge_multiplier: Mapped[float] = mapped_column(Float, nullable=False)
    is_weekend: Mapped[bool] = mapped_column(Boolean, nullable=False)
    recorded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False, index=True
    )


class SurgePrediction(Base):
    """
    Model inference results cached for the next N hours.
    Generated by the Celery background task.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    platform: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    predicted_hour: Mapped[int] = mapped_column(Integer, nullable=False)
    predicted_day_of_week: Mapped[int] = mapped_column(Integer, nullable=False)
    surge_probability: Mapped[float] = mapped_column(Float, nullable=False)
    predicted_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
